global: {}
argocd-config:
  repoUrl: "http://gogs.tools:3000/toolkit/gitops.git"
  project: "openshift-gitops"
  applicationTargets:
  - targetRevision: master
    createNamespace: false
    targetNamespace: "jules-project"
    applications:
     - name: "spmeight"
       path: "dev/spmeight-argocd/spmeight"
       type: helm
     