global: {}
argocd-config:
  repoUrl: "http://gogs.tools:3000/toolkit/gitops.git"
  project: "openshift-gitops"
  applicationTargets:
    - targetRevision: master
      createNamespace: false
      targetNamespace: jules-project
      applications:
        - name: spm
          path: dev/spm
          type: helm
   